# Generated by Django 3.2.5 on 2021-07-15 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_videoproxy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoproxy',
            options={'verbose_name': 'Piblished Video', 'verbose_name_plural': 'Piblished Videos'},
        ),
    ]
